import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAgents } from "@/hooks/use-agents";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { format } from "date-fns";
import { Card, CardContent, CardHeader, CardTitle, } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Cpu, Activity, AlertTriangle, Clock } from "lucide-react";
export default function Agents() {
    var _a = useAgents(), agents = _a.data, isLoading = _a.isLoading;
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-7xl mx-auto", children: [_jsx(PageHeader, { title: "System Agents", description: "Monitor the automated workers fetching, processing, and writing content." }), isLoading ? (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: [1, 2, 3].map(function (i) { return (_jsx("div", { className: "h-48 bg-card rounded-xl border border-border animate-pulse" }, i)); }) })) : (agents === null || agents === void 0 ? void 0 : agents.length) === 0 ? (_jsxs("div", { className: "text-center py-20 bg-card rounded-xl border border-border", children: [_jsx(Cpu, { className: "w-12 h-12 text-muted-foreground mx-auto mb-4" }), _jsx("h3", { className: "text-lg font-medium text-foreground", children: "No Agents configured" })] })) : (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: agents === null || agents === void 0 ? void 0 : agents.map(function (agent) { return (_jsxs(Card, { className: "relative overflow-hidden bg-card border-border/50 shadow-sm hover-elevate", children: [agent.status === 'running' && (_jsx("div", { className: "absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-emerald-400 to-emerald-600 animate-pulse" })), agent.status === 'error' && (_jsx("div", { className: "absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-rose-400 to-rose-600" })), _jsx(CardHeader, { className: "pb-2", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "p-2 rounded-lg ".concat(agent.status === 'running' ? 'bg-emerald-500/10 text-emerald-500' :
                                                    agent.status === 'error' ? 'bg-rose-500/10 text-rose-500' :
                                                        'bg-slate-500/10 text-slate-500'), children: _jsx(Cpu, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx(CardTitle, { className: "text-lg", children: agent.name }), _jsx("p", { className: "text-xs font-medium text-muted-foreground uppercase tracking-wider", children: agent.type })] })] }), _jsx(StatusBadge, { status: agent.status })] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4 mt-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsxs("span", { className: "text-muted-foreground flex items-center gap-1", children: [_jsx(Activity, { className: "w-3.5 h-3.5" }), agent.currentTask || 'Idle'] }), _jsxs("span", { className: "font-mono text-xs", children: [agent.progress || 0, "%"] })] }), _jsx(Progress, { value: agent.progress || 0, className: "h-1.5", indicatorClassName: agent.status === 'error' ? 'bg-rose-500' : 'bg-primary' })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 pt-2", children: [_jsxs("div", { className: "space-y-1", children: [_jsxs("span", { className: "text-xs text-muted-foreground flex items-center gap-1", children: [_jsx(FileText, { className: "w-3 h-3" }), " Processed"] }), _jsx("p", { className: "font-mono font-medium", children: agent.totalProcessed || 0 })] }), _jsxs("div", { className: "space-y-1", children: [_jsxs("span", { className: "text-xs text-muted-foreground flex items-center gap-1", children: [_jsx(AlertTriangle, { className: "w-3 h-3" }), " Errors"] }), _jsx("p", { className: "font-mono font-medium ".concat(agent.errorCount > 0 ? 'text-rose-500' : ''), children: agent.errorCount || 0 })] })] }), agent.lastRun && (_jsxs("div", { className: "text-xs text-muted-foreground flex items-center gap-1 pt-2 border-t border-border/50", children: [_jsx(Clock, { className: "w-3 h-3" }), "Last Run: ", format(new Date(agent.lastRun), 'MMM d, h:mm a')] })), agent.lastError && agent.status === 'error' && (_jsx("div", { className: "p-2 rounded bg-rose-500/10 border border-rose-500/20 text-xs text-rose-600 line-clamp-2 mt-2", children: agent.lastError }))] }) })] }, agent.id)); }) }))] }));
}
// Ensure missing import is available
import { FileText } from "lucide-react";
