import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useStories, useDeleteStory, usePublishStory } from "@/hooks/use-stories";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";
import { Card, CardContent, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { FileText, Trash2, Send, Clock } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
export default function Stories() {
    var _a = useStories(), stories = _a.data, isLoading = _a.isLoading;
    var deleteStory = useDeleteStory();
    var publishStory = usePublishStory();
    var toast = useToast().toast;
    var handlePublish = function (id) {
        publishStory.mutate(id, {
            onSuccess: function () { return toast({ title: "Story Published" }); },
            onError: function (err) { return toast({ title: "Failed to publish", description: err.message, variant: "destructive" }); }
        });
    };
    var handleDelete = function (id) {
        if (confirm("Delete this generated story?")) {
            deleteStory.mutate(id);
        }
    };
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-7xl mx-auto", children: [_jsx(PageHeader, { title: "Generated Stories", description: "Content generated by agents ready for review and publishing." }), isLoading ? (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: [1, 2, 3].map(function (i) { return (_jsx("div", { className: "h-64 bg-card rounded-xl border border-border animate-pulse" }, i)); }) })) : (stories === null || stories === void 0 ? void 0 : stories.length) === 0 ? (_jsxs("div", { className: "text-center py-20 bg-card rounded-xl border border-border", children: [_jsx(FileText, { className: "w-12 h-12 text-muted-foreground mx-auto mb-4" }), _jsx("h3", { className: "text-lg font-medium text-foreground", children: "No stories yet" }), _jsx("p", { className: "text-muted-foreground", children: "Generated content will appear here." })] })) : (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: stories === null || stories === void 0 ? void 0 : stories.map(function (story) {
                    var _a;
                    return (_jsxs(Card, { className: "flex flex-col hover-elevate shadow-sm border-border/50 bg-card", children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx(StatusBadge, { status: story.status }), _jsxs("span", { className: "text-xs text-muted-foreground flex items-center gap-1", children: [_jsx(Clock, { className: "w-3 h-3" }), format(new Date(story.createdAt), 'MMM d')] })] }), _jsx(CardTitle, { className: "text-xl line-clamp-2 leading-tight", children: story.title })] }), _jsxs(CardContent, { className: "flex-1", children: [_jsx("p", { className: "text-muted-foreground text-sm line-clamp-3", children: story.summary || ((_a = story.content) === null || _a === void 0 ? void 0 : _a.substring(0, 150)) + "..." }), story.charts && (_jsx("div", { className: "mt-4 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-500/10 text-indigo-600 text-xs font-medium", children: "Includes Chart Data" }))] }), _jsxs(CardFooter, { className: "pt-3 border-t border-border/50 flex justify-between bg-muted/10", children: [_jsxs(Button, { variant: "ghost", size: "sm", className: "text-destructive hover:bg-destructive/10 hover:text-destructive", onClick: function () { return handleDelete(story.id); }, children: [_jsx(Trash2, { className: "w-4 h-4 mr-2" }), " Delete"] }), story.status !== 'published' && (_jsxs(Button, { size: "sm", className: "bg-primary hover:bg-primary/90", onClick: function () { return handlePublish(story.id); }, disabled: publishStory.isPending, children: [_jsx(Send, { className: "w-4 h-4 mr-2" }), " Publish"] }))] })] }, story.id));
                }) }))] }));
}
