import { useState } from "react";
import { useStories, useCreateStory, useUpdateStory, useDeleteStory, usePublishStory } from "@/hooks/use-stories";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { format } from "date-fns";
import { 
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { FileText, Trash2, Send, Clock, Plus, Pencil } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function Stories() {
  const { data: stories, isLoading } = useStories();
  const createStory = useCreateStory();
  const updateStory = useUpdateStory();
  const deleteStory = useDeleteStory();
  const publishStory = usePublishStory();
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<{ id: number; title: string; content: string; summary?: string; status: string } | null>(null);
  const [form, setForm] = useState({ title: "", content: "", summary: "", status: "draft" });

  const handlePublish = (id: number) => {
    publishStory.mutate(id, {
      onSuccess: () => toast({ title: "Story Published" }),
      onError: (err) => toast({ title: "Failed to publish", description: err.message, variant: "destructive" })
    });
  };

  const handleDelete = (id: number) => {
    if (confirm("Delete this generated story?")) {
      deleteStory.mutate(id);
    }
  };

  const handleUpdate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editing) return;
    updateStory.mutate(
      { id: editing.id, data: { title: form.title, content: form.content, summary: form.summary || undefined, status: form.status } },
      {
        onSuccess: () => {
          setEditing(null);
          toast({ title: "Story updated" });
        },
        onError: (err: Error) => toast({ title: "Error", description: err.message, variant: "destructive" }),
      }
    );
  };

  const handleCreate = (e: React.FormEvent) => {
    e.preventDefault();
    createStory.mutate({ title: form.title, content: form.content, summary: form.summary || undefined, status: "draft" }, {
      onSuccess: () => {
        setOpen(false);
        setForm({ title: "", content: "", summary: "", status: "draft" });
        toast({ title: "Story created" });
      },
      onError: (err: Error) => toast({ title: "Error", description: err.message, variant: "destructive" }),
    });
  };

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto">
      <PageHeader 
        title="Generated Stories" 
        description="Content generated by agents ready for review and publishing."
      >
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button className="bg-gradient-to-r from-primary to-indigo-600 hover:opacity-90">
              <Plus className="w-4 h-4 mr-2" /> Add Story
            </Button>
          </DialogTrigger>
          <DialogContent>
            <form onSubmit={handleCreate}>
              <DialogHeader>
                <DialogTitle>Add Story</DialogTitle>
                <DialogDescription>Create a new story/project.</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid gap-2">
                  <Label htmlFor="title">Title</Label>
                  <Input id="title" value={form.title} onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))} required />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="summary">Summary</Label>
                  <Input id="summary" value={form.summary} onChange={(e) => setForm((f) => ({ ...f, summary: e.target.value }))} placeholder="Optional" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="content">Content</Label>
                  <Textarea id="content" value={form.content} onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))} rows={5} required />
                </div>
              </div>
              <DialogFooter>
                <Button type="submit" disabled={createStory.isPending}>{createStory.isPending ? "Creating..." : "Create"}</Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      </PageHeader>

      {isLoading ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-64 bg-card rounded-xl border border-border animate-pulse" />
          ))}
        </div>
      ) : stories?.length === 0 ? (
        <div className="text-center py-20 bg-card rounded-xl border border-border">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-medium text-foreground">No stories yet</h3>
          <p className="text-muted-foreground">Generated content will appear here.</p>
        </div>
      ) : (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {stories?.map((story: any) => (
            <Card key={story.id} className="flex flex-col hover-elevate shadow-sm border-border/50 bg-card">
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start mb-2">
                  <StatusBadge status={story.status} />
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {story.createdAt ? format(new Date(story.createdAt), 'MMM d') : '—'}
                  </span>
                </div>
                <CardTitle className="text-xl line-clamp-2 leading-tight">
                  {story.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="flex-1">
                <p className="text-muted-foreground text-sm line-clamp-3">
                  {story.summary || story.content?.substring(0, 150) + "..."}
                </p>
                {story.charts && (
                  <div className="mt-4 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-500/10 text-indigo-600 text-xs font-medium">
                    Includes Chart Data
                  </div>
                )}
              </CardContent>
              <CardFooter className="pt-3 border-t border-border/50 flex justify-between bg-muted/10">
                <div className="flex gap-2">
                  <Button variant="ghost" size="sm" onClick={() => { setEditing(story); setForm({ title: story.title, content: story.content || "", summary: story.summary || "", status: story.status }); }}>
                    <Pencil className="w-4 h-4 mr-2" /> Edit
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="text-destructive hover:bg-destructive/10 hover:text-destructive"
                    onClick={() => handleDelete(story.id)}
                  >
                    <Trash2 className="w-4 h-4 mr-2" /> Delete
                  </Button>
                </div>
                {story.status !== 'published' && (
                  <Button 
                    size="sm" 
                    className="bg-primary hover:bg-primary/90"
                    onClick={() => handlePublish(story.id)}
                    disabled={publishStory.isPending}
                  >
                    <Send className="w-4 h-4 mr-2" /> Publish
                  </Button>
                )}
              </CardFooter>
            </Card>
          ))}
        </div>
      )}

      {editing && (
        <Dialog open={!!editing} onOpenChange={() => setEditing(null)}>
          <DialogContent>
            <form onSubmit={handleUpdate}>
              <DialogHeader>
                <DialogTitle>Edit Story</DialogTitle>
                <DialogDescription>Update the story content and status.</DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid gap-2">
                  <Label>Title</Label>
                  <Input value={form.title} onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))} required />
                </div>
                <div className="grid gap-2">
                  <Label>Summary</Label>
                  <Input value={form.summary} onChange={(e) => setForm((f) => ({ ...f, summary: e.target.value }))} placeholder="Optional" />
                </div>
                <div className="grid gap-2">
                  <Label>Content</Label>
                  <Textarea value={form.content} onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))} rows={5} required />
                </div>
                <div className="grid gap-2">
                  <Label>Status</Label>
                  <Input value={form.status} onChange={(e) => setForm((f) => ({ ...f, status: e.target.value }))} placeholder="draft | published" />
                </div>
              </div>
              <DialogFooter>
                <Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button>
                <Button type="submit" disabled={updateStory.isPending}>{updateStory.isPending ? "Saving..." : "Save"}</Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}
