var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useStories, useCreateStory, useUpdateStory, useDeleteStory, usePublishStory } from "@/hooks/use-stories";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { format } from "date-fns";
import { Card, CardContent, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { FileText, Trash2, Send, Clock, Plus, Pencil } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
export default function Stories() {
    var _a = useStories(), stories = _a.data, isLoading = _a.isLoading;
    var createStory = useCreateStory();
    var updateStory = useUpdateStory();
    var deleteStory = useDeleteStory();
    var publishStory = usePublishStory();
    var toast = useToast().toast;
    var _b = useState(false), open = _b[0], setOpen = _b[1];
    var _c = useState(null), editing = _c[0], setEditing = _c[1];
    var _d = useState({ title: "", content: "", summary: "", status: "draft" }), form = _d[0], setForm = _d[1];
    var handlePublish = function (id) {
        publishStory.mutate(id, {
            onSuccess: function () { return toast({ title: "Story Published" }); },
            onError: function (err) { return toast({ title: "Failed to publish", description: err.message, variant: "destructive" }); }
        });
    };
    var handleDelete = function (id) {
        if (confirm("Delete this generated story?")) {
            deleteStory.mutate(id);
        }
    };
    var handleUpdate = function (e) {
        e.preventDefault();
        if (!editing)
            return;
        updateStory.mutate({ id: editing.id, data: { title: form.title, content: form.content, summary: form.summary || undefined, status: form.status } }, {
            onSuccess: function () {
                setEditing(null);
                toast({ title: "Story updated" });
            },
            onError: function (err) { return toast({ title: "Error", description: err.message, variant: "destructive" }); },
        });
    };
    var handleCreate = function (e) {
        e.preventDefault();
        createStory.mutate({ title: form.title, content: form.content, summary: form.summary || undefined, status: "draft" }, {
            onSuccess: function () {
                setOpen(false);
                setForm({ title: "", content: "", summary: "", status: "draft" });
                toast({ title: "Story created" });
            },
            onError: function (err) { return toast({ title: "Error", description: err.message, variant: "destructive" }); },
        });
    };
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-7xl mx-auto", children: [_jsx(PageHeader, { title: "Generated Stories", description: "Content generated by agents ready for review and publishing.", children: _jsxs(Dialog, { open: open, onOpenChange: setOpen, children: [_jsx(DialogTrigger, { asChild: true, children: _jsxs(Button, { className: "bg-gradient-to-r from-primary to-indigo-600 hover:opacity-90", children: [_jsx(Plus, { className: "w-4 h-4 mr-2" }), " Add Story"] }) }), _jsx(DialogContent, { children: _jsxs("form", { onSubmit: handleCreate, children: [_jsxs(DialogHeader, { children: [_jsx(DialogTitle, { children: "Add Story" }), _jsx(DialogDescription, { children: "Create a new story/project." })] }), _jsxs("div", { className: "grid gap-4 py-4", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "title", children: "Title" }), _jsx(Input, { id: "title", value: form.title, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { title: e.target.value })); }); }, required: true })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "summary", children: "Summary" }), _jsx(Input, { id: "summary", value: form.summary, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { summary: e.target.value })); }); }, placeholder: "Optional" })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { htmlFor: "content", children: "Content" }), _jsx(Textarea, { id: "content", value: form.content, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { content: e.target.value })); }); }, rows: 5, required: true })] })] }), _jsx(DialogFooter, { children: _jsx(Button, { type: "submit", disabled: createStory.isPending, children: createStory.isPending ? "Creating..." : "Create" }) })] }) })] }) }), isLoading ? (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: [1, 2, 3].map(function (i) { return (_jsx("div", { className: "h-64 bg-card rounded-xl border border-border animate-pulse" }, i)); }) })) : (stories === null || stories === void 0 ? void 0 : stories.length) === 0 ? (_jsxs("div", { className: "text-center py-20 bg-card rounded-xl border border-border", children: [_jsx(FileText, { className: "w-12 h-12 text-muted-foreground mx-auto mb-4" }), _jsx("h3", { className: "text-lg font-medium text-foreground", children: "No stories yet" }), _jsx("p", { className: "text-muted-foreground", children: "Generated content will appear here." })] })) : (_jsx("div", { className: "grid gap-6 md:grid-cols-2 lg:grid-cols-3", children: stories === null || stories === void 0 ? void 0 : stories.map(function (story) {
                    var _a;
                    return (_jsxs(Card, { className: "flex flex-col hover-elevate shadow-sm border-border/50 bg-card", children: [_jsxs(CardHeader, { className: "pb-3", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx(StatusBadge, { status: story.status }), _jsxs("span", { className: "text-xs text-muted-foreground flex items-center gap-1", children: [_jsx(Clock, { className: "w-3 h-3" }), story.createdAt ? format(new Date(story.createdAt), 'MMM d') : '—'] })] }), _jsx(CardTitle, { className: "text-xl line-clamp-2 leading-tight", children: story.title })] }), _jsxs(CardContent, { className: "flex-1", children: [_jsx("p", { className: "text-muted-foreground text-sm line-clamp-3", children: story.summary || ((_a = story.content) === null || _a === void 0 ? void 0 : _a.substring(0, 150)) + "..." }), story.charts && (_jsx("div", { className: "mt-4 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-500/10 text-indigo-600 text-xs font-medium", children: "Includes Chart Data" }))] }), _jsxs(CardFooter, { className: "pt-3 border-t border-border/50 flex justify-between bg-muted/10", children: [_jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { variant: "ghost", size: "sm", onClick: function () { setEditing(story); setForm({ title: story.title, content: story.content || "", summary: story.summary || "", status: story.status }); }, children: [_jsx(Pencil, { className: "w-4 h-4 mr-2" }), " Edit"] }), _jsxs(Button, { variant: "ghost", size: "sm", className: "text-destructive hover:bg-destructive/10 hover:text-destructive", onClick: function () { return handleDelete(story.id); }, children: [_jsx(Trash2, { className: "w-4 h-4 mr-2" }), " Delete"] })] }), story.status !== 'published' && (_jsxs(Button, { size: "sm", className: "bg-primary hover:bg-primary/90", onClick: function () { return handlePublish(story.id); }, disabled: publishStory.isPending, children: [_jsx(Send, { className: "w-4 h-4 mr-2" }), " Publish"] }))] })] }, story.id));
                }) })), editing && (_jsx(Dialog, { open: !!editing, onOpenChange: function () { return setEditing(null); }, children: _jsx(DialogContent, { children: _jsxs("form", { onSubmit: handleUpdate, children: [_jsxs(DialogHeader, { children: [_jsx(DialogTitle, { children: "Edit Story" }), _jsx(DialogDescription, { children: "Update the story content and status." })] }), _jsxs("div", { className: "grid gap-4 py-4", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { children: "Title" }), _jsx(Input, { value: form.title, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { title: e.target.value })); }); }, required: true })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { children: "Summary" }), _jsx(Input, { value: form.summary, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { summary: e.target.value })); }); }, placeholder: "Optional" })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { children: "Content" }), _jsx(Textarea, { value: form.content, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { content: e.target.value })); }); }, rows: 5, required: true })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx(Label, { children: "Status" }), _jsx(Input, { value: form.status, onChange: function (e) { return setForm(function (f) { return (__assign(__assign({}, f), { status: e.target.value })); }); }, placeholder: "draft | published" })] })] }), _jsxs(DialogFooter, { children: [_jsx(Button, { type: "button", variant: "outline", onClick: function () { return setEditing(null); }, children: "Cancel" }), _jsx(Button, { type: "submit", disabled: updateStory.isPending, children: updateStory.isPending ? "Saving..." : "Save" })] })] }) }) }))] }));
}
