import { useState } from "react";
import { useStories, useDeleteStory, usePublishStory } from "@/hooks/use-stories";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";
import { 
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { FileText, Trash2, Send, Clock } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function Stories() {
  const { data: stories, isLoading } = useStories();
  const deleteStory = useDeleteStory();
  const publishStory = usePublishStory();
  const { toast } = useToast();

  const handlePublish = (id: number) => {
    publishStory.mutate(id, {
      onSuccess: () => toast({ title: "Story Published" }),
      onError: (err) => toast({ title: "Failed to publish", description: err.message, variant: "destructive" })
    });
  };

  const handleDelete = (id: number) => {
    if (confirm("Delete this generated story?")) {
      deleteStory.mutate(id);
    }
  };

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto">
      <PageHeader 
        title="Generated Stories" 
        description="Content generated by agents ready for review and publishing."
      />

      {isLoading ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-64 bg-card rounded-xl border border-border animate-pulse" />
          ))}
        </div>
      ) : stories?.length === 0 ? (
        <div className="text-center py-20 bg-card rounded-xl border border-border">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-medium text-foreground">No stories yet</h3>
          <p className="text-muted-foreground">Generated content will appear here.</p>
        </div>
      ) : (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {stories?.map((story: any) => (
            <Card key={story.id} className="flex flex-col hover-elevate shadow-sm border-border/50 bg-card">
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start mb-2">
                  <StatusBadge status={story.status} />
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {format(new Date(story.createdAt), 'MMM d')}
                  </span>
                </div>
                <CardTitle className="text-xl line-clamp-2 leading-tight">
                  {story.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="flex-1">
                <p className="text-muted-foreground text-sm line-clamp-3">
                  {story.summary || story.content?.substring(0, 150) + "..."}
                </p>
                {story.charts && (
                  <div className="mt-4 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-500/10 text-indigo-600 text-xs font-medium">
                    Includes Chart Data
                  </div>
                )}
              </CardContent>
              <CardFooter className="pt-3 border-t border-border/50 flex justify-between bg-muted/10">
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="text-destructive hover:bg-destructive/10 hover:text-destructive"
                  onClick={() => handleDelete(story.id)}
                >
                  <Trash2 className="w-4 h-4 mr-2" /> Delete
                </Button>
                {story.status !== 'published' && (
                  <Button 
                    size="sm" 
                    className="bg-primary hover:bg-primary/90"
                    onClick={() => handlePublish(story.id)}
                    disabled={publishStory.isPending}
                  >
                    <Send className="w-4 h-4 mr-2" /> Publish
                  </Button>
                )}
              </CardFooter>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
